Pauta da Reunião 1 (16/03)
2020-1-Eulivro/Wiki pull request #15
Opened 2020-03-18 00:45 UTC by micaellagouveia

Neste pull request se realizou:
* 11 - Documentação da pauta da reunião do dia 16/03;

2020-03-18 01:11 UTC, ghost requested changes
Tenta mudar o nome das pastas para deixar tudo em inglês para ficar padronizado. Só isso mesmo!

2020-03-18 20:28 UTC, sofiapatrocinio commented
Só falta colocar na side bar, como 'reuniões' ou algo do tipo

2020-03-18 20:29 UTC, sofiapatrocinio requested changes

2020-03-18 20:29 UTC, sofiapatrocinio commented on docs/PautaReuniões/reuniao1.md
> +# Reunião 1
Só falta colocar na side bar, como 'reuniões' ou algo do tipo

2020-03-18 23:59 UTC, micaellagouveia commented on docs/PautaReuniões/reuniao1.md
> +# Reunião 1
Arrumado.

2020-03-19 19:54 UTC, GabrielDVpereira reviewed
Revisado

2020-03-19 20:05 UTC, ghost approved these changes
Tudo certo conforme as alterações solicitadas

2020-03-19 20:13 UTC, gitgabiru commented
Revisado.

2020-03-19 20:45 UTC, pedroeagle approved these changes

2020-03-19 20:48 UTC, sofiapatrocinio approved these changes

2020-03-19 21:07 UTC, merged